import { Suspense } from "react";
import type { Metadata } from "next";
import LoginClient from "./LoginClient";

export const metadata: Metadata = {
 title: "Join VYA — The first online department store for vintage and secondhand.",
 description: "Discover the best vintage and secondhand stores, all in one place. Sign in or create an account to be added to our pilot.",
 openGraph: {
 title: "The world's best vintage, all in one place.",
 description: "Discover the best vintage and secondhand stores, all in one place. Sign in or create an account to be added to our pilot.",
 url: "https://vyaplatform.com/login",
 siteName: "VYA",
 // og:image is generated by app/login/opengraph-image.tsx (the hero card).
 type: "website",
 },
 twitter: {
 card: "summary_large_image",
 title: "The world's best vintage, all in one place.",
 description: "Discover the best vintage and secondhand stores, all in one place. Sign in or create an account to be added to our pilot.",
 },
};

export default function LoginPage() {
 return (
 <Suspense fallback={null}>
 <LoginClient />
 </Suspense>
 );
}
